# Generated by Django 5.1.7 on 2025-09-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_app', '0003_laptop_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
    ]
