# Generated by Django 5.1.7 on 2025-09-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_app', '0004_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
