# Generated by Django 5.1.7 on 2025-09-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_app', '0005_alter_contact_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('level_of_education', models.CharField(choices=[('bca', 'bca'), ('mca', 'mca'), ('cse', 'cse'), ('diploma', 'diploma')], max_length=100)),
                ('course_interested', models.CharField(choices=[('mern stack', 'mern stack'), ('full stack', 'full stack'), ('artificial intelligence', 'artificial intelligence'), ('machine learning', 'machine learning')], max_length=100)),
                ('is_subscribe', models.BooleanField(default=False)),
            ],
        ),
    ]
