# Generated by Django 5.2.5 on 2025-09-22 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_app', '0006_inquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('discription', models.TextField()),
                ('overview', models.TextField()),
                ('learn', models.TextField()),
                ('content', models.TextField()),
                ('image', models.FileField(upload_to='')),
                ('course_level', models.CharField(max_length=100)),
                ('course_duration', models.CharField(max_length=100)),
                ('course_lectures', models.CharField(max_length=100)),
                ('course_quizzes', models.CharField(max_length=100)),
                ('course_language', models.CharField(max_length=100)),
                ('course_assessments', models.BooleanField()),
                ('course_certificate', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academy_app.category')),
            ],
        ),
    ]
